version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8080:80
    volumes:
    - ./server:/src
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build: .
    volumes:
    - ./server:/src
    working_dir: /src
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306